package Vista;

/**
 *
 * @author Alicia Huamani
 */
import Controlador.ControladorCheckOut;
import Modelo.CheckOut.ArbolCheckOut;
import Modelo.Habitacion.ListaCircularHabitaciones;
import Modelo.Historial.PilaHistorialReserva;
import Modelo.Reservas.ListaDobleReservas;

public class PanelPrincipal extends javax.swing.JFrame {

    private ArbolCheckOut arbolCheckOut;
    private ListaDobleReservas listaTotalReservas;
    private ListaCircularHabitaciones listaHabitaciones;
    private PilaHistorialReserva pilaHistorial;

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal(ArbolCheckOut arbolCheckOut,
                           ListaDobleReservas listaTotalReservas,
                           ListaCircularHabitaciones listaHabitaciones,
                           PilaHistorialReserva pilaHistorial) {
        this.arbolCheckOut = arbolCheckOut;
        this.listaTotalReservas = listaTotalReservas;
        this.listaHabitaciones = listaHabitaciones;
        this.pilaHistorial = pilaHistorial;
        initComponents();
    }

    // Overload constructor for NetBeans GUI builder compatibility if needed
    public PanelPrincipal() {
        initComponents();
        // This constructor might lead to NullPointerExceptions if dependencies are not set
        // and actions requiring them are triggered. Consider initializing with defaults
        // or disabling components if dependencies are null.
        System.err.println("Warning: PanelPrincipal created without dependencies. CheckOut functionality may fail.");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Will change this in next step

        jLabel1.setText("Formularios");

        jButton1.setText("Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Habitacion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reserva");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Check - Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3)
                                .addComponent(jButton1)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PanelCliente panelCliente = new PanelCliente();
        panelCliente.setVisible(true);
        this.dispose();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PanelHabitaciones panelHabitaciones = new PanelHabitaciones();
        panelHabitaciones.setVisible(true);
        this.dispose();
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PanelReserva panelReserva = new PanelReserva();
        panelReserva.setVisible(true);
        this.dispose();
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PanelCheckOut panelCheckOut = new PanelCheckOut();
        // Ensure dependencies were injected into PanelPrincipal
        if (this.arbolCheckOut == null || this.listaTotalReservas == null || this.listaHabitaciones == null || this.pilaHistorial == null) {
            System.err.println("Error: Dependencies in PanelPrincipal are null. Cannot create PanelCheckOut properly.");
            // Optionally, show a JOptionPane error to the user here
            javax.swing.JOptionPane.showMessageDialog(this, "Error de configuración interna. No se puede abrir Check-Out.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        ControladorCheckOut controladorCheckOut = new ControladorCheckOut(panelCheckOut, 
                                                                        this.arbolCheckOut, 
                                                                        this.listaTotalReservas, 
                                                                        this.listaHabitaciones, 
                                                                        this.pilaHistorial);
        panelCheckOut.setControlador(controladorCheckOut);
        panelCheckOut.setVisible(true);
        this.dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
